# Generated by Django 4.0.3 on 2022-03-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_department'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='groups',
            field=models.ManyToManyField(help_text='The department this user belongs to. An Employee will get all permissions granted to  their department.', related_name='user_department', related_query_name='employee', to='auth.department', verbose_name='departments'),
        ),
    ]
