# Generated by Django 4.0.3 on 2022-03-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_affiliation_delete_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='group_ptr',
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
