# Generated by Django 4.0.3 on 2022-03-15 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_affiliation_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
