# Generated by Django 4.0.3 on 2022-03-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_department'),
        ('core', '0011_alter_affiliation_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
