# Generated by Django 4.0.3 on 2022-04-12 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update date')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update date')),
                ('first_name', models.CharField(max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(max_length=150, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='phone number')),
                ('company_name', models.CharField(max_length=50, verbose_name='company name')),
                ('mobile', models.CharField(blank=True, max_length=15, verbose_name='mobile phone number')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update date')),
                ('amount_in_cts', models.IntegerField(verbose_name='amount (in cts)')),
                ('due_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='due_date')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to='api.client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientAssignment',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.assignment')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.assignment',),
        ),
        migrations.CreateModel(
            name='ContractNegotiationAssignment',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.assignment')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.assignment',),
        ),
        migrations.CreateModel(
            name='ContractPaymentAssignment',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.assignment')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.assignment',),
        ),
        migrations.CreateModel(
            name='ContractSignatureAssignment',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.assignment')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.assignment',),
        ),
        migrations.CreateModel(
            name='EventAssignment',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.assignment')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.assignment',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('date_updated', models.DateTimeField(auto_now_add=True, null=True, verbose_name='update date')),
                ('name', models.CharField(max_length=50, verbose_name='event_name')),
                ('status', models.IntegerField(choices=[(1, 'created'), (2, 'ongoing'), (3, 'terminated')])),
                ('begin_date', models.DateTimeField(verbose_name='begin date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('attendees', models.IntegerField(default=0, verbose_name='attendees')),
                ('notes', models.TextField(verbose_name='notes')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_contract', to='api.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
