# Generated by Django 4.0.3 on 2022-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='Test Event', max_length=50, verbose_name='event_name'),
            preserve_default=False,
        ),
    ]
