# Generated by Django 4.0.3 on 2022-03-18 16:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 18, 16, 16, 9, 11633, tzinfo=utc), verbose_name='due_date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(1, 'created'), (2, 'ongoing'), (3, 'terminated')], max_length=10),
        ),
    ]
