# Generated by Django 4.0.3 on 2022-03-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contract_amount_in_cts_contract_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='phone number'),
        ),
    ]
