# Generated by Django 4.0.2 on 2022-03-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='update date'),
        ),
    ]
