# Generated by Django 4.0.2 on 2022-03-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='clientassignment',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='update date'),
        ),
        migrations.AlterField(
            model_name='contractassignment',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='update date'),
        ),
    ]
